#!/bin/bash --login
#
#PBS -l walltime=24:00:00
#PBS -l select=11
##PBES -j oe
#PBS -m abe -M a.blanca-romero@imperial.ac.uk
#PBS -N S_conv
#PBS -A e05-gener-nic

# Load the Quantum Espresso module
module add espresso

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR
echo '$PBS_O_WORKDIR=' $PBS_O_WORKDIR

# Make sure temporary files go to the /work filesystem
export TMPDIR=$PBS_O_WORKDIR
export ESPRESSO_TMPDIR=$PBS_O_WORKDIR

module list
which pw.x
which bands.x
which dos.x
which projwfc.x
which plotband.x

case=`echo  $PBS_O_WORKDIR`
case=${case##*/}

# Run the Quantum Espresso executable "pw.x"
S_FM_RUN_U_occu_cx1_TEMPDIR_primitive_smearing_mv_conventional.sh -m "aprun -n 132 " -a "4" -w "95" -f "800" -c "vc-relax" -t "86000" -g "PBE" -k "yes" -z "yes" > OUT_S_primitive_FM_RUN_U_occu_paw_conv
#prun -n 96 pw.x -nband 1 -ntg 1 -inp si.scf.david.in > si.scf.david.out

##rm -r $case.save
