#!/bin/bash --login
#
#PBS -l walltime=24:00:00
#PBS -l select=3
##PBES -j oe
#PBS -m abe -M a.blanca-romero@imperial.ac.uk
#PBS -N ULR
#PBS -A e05-gener-nic

# Load the Quantum Espresso module
module add espresso

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR
echo '$PBS_O_WORKDIR=' $PBS_O_WORKDIR

# Make sure temporary files go to the /work filesystem
export TMPDIR=$PBS_O_WORKDIR
export ESPRESSO_TMPDIR=$PBS_O_WORKDIR

module list
which pw.x
which bands.x 
which dos.x 
which projwfc.x
which plotband.x 

case=`echo  $PBS_O_WORKDIR`
case=${case##*/}


# Run the Quantum Espresso executable "pw.x"
#New script with input of alpha perturbations, type of atoms, and total number of atoms in the cell
DFTU_Fe3O2_Lyly_TEMP_AFM_Natoms_alphas_ntg.sh -m "aprun -n 48" -w 95 -f 800 -g "PBE" -a "8" -t "3" -n "40" -a "8" -s "4" -z "-0.15 -0.07 0.00 0.07 0.15" -d "yes"  > OUTPUT_DFTULR_$case
